language: java
jdk: openjdk11

addons:
  sonarcloud:
    organization: "spring-petclinic"
    token:
      secure: "vAaR4lrfSTr0Mjsc8YkNzttwG18JjT11R85IrsIXjWJDHx8nTzhHgB4bku0aRQQheTRs1INhl9IJE2kmiHrqiiLUTIF9L5UYVYjyjeDVQnK5W1ycwOYZKcPuYFkFDx8f/8qY2b/EiIyvSr9OkmrG3HP0mjcoaLjQjCTnVW6TEVyPdbIEDjCQHK8rLT1jnmOvGJHWfE1K++KHUhKho+ZY+U7YYGk0YpLPp5EZGCy/BfR3A/wtF1IucBYzNEwHIE89bP92TWNrNudYttqI9JaB6bu0NPWF43Rr8p6zxrBDxfGR2lcTtqOJYjCMN+aoxoFKLtz0erbv3thqnIGfFxaOAUtrwUHzikXV8Zqpi9iUHOy1KXjGrm1Nqce6CYeu8sR/EFwJiZ/zg10OszvYXEf+JznBN+6Nyur0Pt4gh3vGwYOJBe5+iSVou2UKqsh34Zzaq1AuBO731IswF7v+PshazSWZcyLoh6v9ZH/lSgow6OKfH0+BnZX5ktCAyvlLuNbhZWp+V+4L3JOMYkE3OjXWuYFVBgQUo0zK+Ox9L76wYEv9v5GUixXeobyYSFdgUqZavQVwMIIXujP5hbiz9SbzyiNwXZn4C83zjiXStt6R66trUVQ64swlITNxxU+w3opGz16amaYGYLXuPARr2UOTeQYmYhSwiNSRPDBmFXSBFVw="

script:
  # the following command line builds the project, runs the tests with coverage and then execute the SonarCloud analysis
  - mvn clean verify sonar:sonar -Pcoverage -Dsonar.projectKey=spring-petclinic_spring-framework-petclinic

cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'
