# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities
from selenium.webdriver.chrome.service import Service
from webdriver_manager.chrome import ChromeDriverManager
from selenium.webdriver.chrome.options import Options

<<<<<<< HEAD
f = open('public_ip', 'r')
output = f.read()
f.close()
ip = output[21:-2]

print(ip)
=======

# with open('public_ip.json') as f:
#    data = json.load(f)
# print(data)

f = open('public_ip', 'r')
public_ip = f.read()
f.close()
hardcodedIP = "137.117.177.136"
x = public_ip[21:-2]
type(hardcodedIP)
>>>>>>> 2f3d239ac21c2d474740179e628c49dae524b2d4

url_link = "http://%s:8080/petclinic/"%public_ip

# type(x)
print('Output: ', x, type(x))
print('Hardcoded: ', hardcodedIP, type(hardcodedIP))
class TestProvision():
  def setup_method(self, method):
    options = Options()
    #options.binary_location = "/home/efe/Desktop/Selenium/scripts"
    #"/home/vsts/.wdm/drivers/chromedriver/linux64/103.0.5060.53"
    options.add_argument("/home/efe/.config/google-chrome/'Profile 6'")
    options.add_argument("--no-sandbox") 
    options.add_argument("--disable-extensions")
    options.add_argument("--disable-dev-shm-usage") 
    options.add_argument("--start-maximized")
    options.add_argument("--headless")
    self.driver = webdriver.Chrome(service=Service(ChromeDriverManager().install()),options=options)
    self.vars = {}
  
  def test_provision(self):
<<<<<<< HEAD
    # self.driver.get(f"http://{hardcodedIP}:8080/petclinic/")
    self.driver.get(url_link)
=======
    self.driver.get(url_link)
    #self.driver.get(f"http://{x}:8080/petclinic/")
    #self.driver.get("http://137.117.177.136:8080/petclinic/")
>>>>>>> 2f3d239ac21c2d474740179e628c49dae524b2d4
    self.driver.set_window_size(1416, 831)
    self.driver.find_element(By.CSS_SELECTOR, "li:nth-child(3) span:nth-child(2)").click()
    self.driver.find_element(By.CSS_SELECTOR, "li:nth-child(4) > a").click()
    self.driver.find_element(By.CSS_SELECTOR, "li:nth-child(2) span:nth-child(2)").click()
    self.driver.find_element(By.LINK_TEXT, "Add Owner").click()
    self.driver.find_element(By.CSS_SELECTOR, ".active > a").click()
    self.driver.find_element(By.CSS_SELECTOR, ".btn:nth-child(1)").click()
    self.driver.find_element(By.LINK_TEXT, "Betty Davis").click()
    self.driver.find_element(By.LINK_TEXT, "Edit Owner").click()
    self.driver.find_element(By.CSS_SELECTOR, ".btn").click()
    self.driver.find_element(By.LINK_TEXT, "Add New Pet").click()
    self.driver.find_element(By.CSS_SELECTOR, ".active > a").click()
  
