# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestFirstTest():
  def setup_method(self, method):
    self.driver = webdriver.Firefox()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_firstTest(self):
    self.driver.get("https://petclinic-azure-app.azurewebsites.net/petclinic/")
    self.driver.set_window_size(1350, 800)
    self.driver.find_element(By.CSS_SELECTOR, "li:nth-child(4) span:nth-child(2)").click()
    self.driver.find_element(By.CSS_SELECTOR, "li:nth-child(3) > a").click()
    self.driver.find_element(By.CSS_SELECTOR, "li:nth-child(2) > a").click()
    self.driver.find_element(By.NAME, "lastName").click()
    self.driver.find_element(By.NAME, "lastName").click()
    self.driver.find_element(By.NAME, "lastName").send_keys("kaya")
    self.driver.find_element(By.CSS_SELECTOR, ".btn:nth-child(1)").click()
    self.driver.find_element(By.LINK_TEXT, "Edit Owner").click()
    self.driver.find_element(By.CSS_SELECTOR, ".btn").click()
    self.driver.find_element(By.LINK_TEXT, "Add New Pet").click()
    self.driver.find_element(By.ID, "name").click()
    self.driver.find_element(By.ID, "name").send_keys("Fikkie3")
    self.driver.find_element(By.ID, "birthDate").click()
    self.driver.find_element(By.CSS_SELECTOR, ".ui-icon-circle-triangle-w").click()
    self.driver.find_element(By.CSS_SELECTOR, ".ui-icon-circle-triangle-w").click()
    self.driver.find_element(By.CSS_SELECTOR, ".ui-icon-circle-triangle-w").click()
    self.driver.find_element(By.CSS_SELECTOR, ".ui-icon-circle-triangle-w").click()
    self.driver.find_element(By.CSS_SELECTOR, ".ui-icon-circle-triangle-w").click()
    self.driver.find_element(By.CSS_SELECTOR, ".ui-icon-circle-triangle-w").click()
    self.driver.find_element(By.LINK_TEXT, "1").click()
    dropdown = self.driver.find_element(By.ID, "type")
    dropdown.find_element(By.XPATH, "//option[. = 'dog']").click()
    self.driver.find_element(By.CSS_SELECTOR, "option:nth-child(3)").click()
    self.driver.find_element(By.CSS_SELECTOR, ".btn").click()
    self.driver.find_element(By.LINK_TEXT, "Add Visit").click()
    self.driver.find_element(By.ID, "description").click()
    self.driver.find_element(By.ID, "description").send_keys("doggo")
    self.driver.find_element(By.CSS_SELECTOR, ".btn").click()
    self.driver.find_element(By.LINK_TEXT, "Edit Pet").click()
    self.driver.find_element(By.CSS_SELECTOR, ".btn").click()
    self.driver.find_element(By.CSS_SELECTOR, ".navbar-brand > span").click()
    self.driver.find_element(By.CSS_SELECTOR, "li:nth-child(2) > a").click()
    self.driver.find_element(By.CSS_SELECTOR, ".btn:nth-child(1)").click()
    self.driver.find_element(By.LINK_TEXT, "George Franklin").click()
    self.driver.find_element(By.CSS_SELECTOR, ".active span:nth-child(2)").click()
    self.driver.find_element(By.LINK_TEXT, "Add Owner").click()
    self.driver.find_element(By.ID, "firstName").click()
    self.driver.find_element(By.ID, "firstName").send_keys("test")
    self.driver.find_element(By.ID, "lastName").send_keys("user")
    self.driver.find_element(By.ID, "address").click()
    self.driver.find_element(By.ID, "address").click()
    self.driver.find_element(By.ID, "address").send_keys("testingstreet")
    self.driver.find_element(By.ID, "city").click()
    self.driver.find_element(By.ID, "city").send_keys("Amsterdam")
    self.driver.find_element(By.ID, "telephone").click()
    self.driver.find_element(By.ID, "telephone").send_keys("061234567")
    self.driver.find_element(By.CSS_SELECTOR, ".btn").click()
    self.driver.find_element(By.CSS_SELECTOR, ".navbar-brand > span").click()
  
