# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities
from selenium.webdriver.chrome.service import Service
from webdriver_manager.chrome import ChromeDriverManager

class TestRealTest():
  def setup_method(self, method):
    self.driver = webdriver.Chrome(service=Service(ChromeDriverManager().install()))
    self.vars = {}

  def teardown_method(self, method):
    self.driver.quit()
  
  def test_realTest(self):
    self.driver.get("https://petclinic-azure-app.azurewebsites.net/petclinic/")
    self.driver.set_window_size(1416, 831)
    self.driver.find_element(By.CSS_SELECTOR, "li:nth-child(3) span:nth-child(2)").click()
    self.driver.find_element(By.CSS_SELECTOR, "li:nth-child(4) > a").click()
    self.driver.find_element(By.CSS_SELECTOR, "li:nth-child(2) span:nth-child(2)").click()
    self.driver.find_element(By.LINK_TEXT, "Add Owner").click()
    self.driver.find_element(By.CSS_SELECTOR, ".active > a").click()
    self.driver.find_element(By.CSS_SELECTOR, ".btn:nth-child(1)").click()
    self.driver.find_element(By.LINK_TEXT, "Betty Davis").click()
    self.driver.find_element(By.LINK_TEXT, "Edit Owner").click()
    self.driver.find_element(By.CSS_SELECTOR, ".btn").click()
    self.driver.find_element(By.LINK_TEXT, "Add New Pet").click()
    self.driver.find_element(By.CSS_SELECTOR, ".active > a").click()
  
